name: MLOps Pipeline for Fake News Detection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r instructions.txt

    # Step 3: Extract ZIP File
    - name: Extract Dataset ZIP
      run: |
        mkdir dataset
        unzip fake_news_final.zip -d dataset/
        echo "Dataset extracted."

    # Step 4: Validate and Clean Dataset
    - name: Run Dataset Cleaning Script
      run: python scripts/clean_dataset.py

     # Step 5: Train ML Model
    - name: Train Model
      run: |
        python scripts/train_model.py

    # Step 6: Dockerize the Application
    - name: Build Docker Image
      run: docker build -t anmolmishra334/fake_news_detection:${{ github.run_number }} .
      
    # Step 7: Docker Image Push t DockerHub
    - name: Push Docker Image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push  anmolmishra334/fake_news_detection:${{ github.run_number }}

    # Step 7: Pull the Latest Docker Image and Run App
    - name: Run Application
      run: |
        docker pull username/fake-news-app:${{ github.run_number }}
        docker run -d -p 5000:5000  anmolmishra334/fake_news_detection:${{ github.run_number }}

    # Step 8: Run Security Analysis
    - name: Run OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.6.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   
