name: MLOps Pipeline for Fake News Detection

permissions:
  security-events: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      # Step 3: Install Python Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r instructions.txt

      # Step 4: Extract Dataset ZIP
      - name: Extract Dataset ZIP
        run: |
          mkdir -p dataset
          unzip fake_news_final.zip -d dataset/
          echo "Dataset extracted."

      # Step 5: Run Dataset Cleaning Script
      - name: Run Dataset Cleaning Script
        run: python scripts/clean_dataset.py

      # Step 6: Clone GitHub Repository
      - name: Clone GitHub Repository
        run: |
          git clone https://github.com/anmolmishra334/Fake-News-Detection-NLP dataset/git_repo_FND
          echo "Repository cloned successfully."
   
      # Step 7: Train ML Model
      - name: Train Model
        run: |
          python scripts/train_model.py
          echo "Model trained successfully."
        
      # Step 4: Replace Old Model Files
      - name: Replace Model Files
        run: |
          rm -f dataset/git_repo_FND/model.pkl
          rm -f Fake_News_App/model.pkl
          cp dataset/new_model_folder/model.pkl dataset/git_repo_FND/
          cp dataset/new_model_folder/model.pkl Fake_News_App/

    # Step 5: Configure Git and Push Changes
      - name: Configure Git and Push Changes
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_CRED }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "anmol.mishra334@gmail.com"

          git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/anmolmishra334/Fake-News-Detection-NLP.git

          NEW_BRANCH_NAME="feature/new_model_${GITHUB_RUN_NUMBER}"
          git checkout -b $NEW_BRANCH_NAME

          git add dataset/git_repo_FND/model.pkl Fake_News_App/model.pkl
          git commit -m "Update model.pkl files for run #${GITHUB_RUN_NUMBER}"

          git push origin $NEW_BRANCH_NAME

      # Step 6: Create Pull Request
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_BRANCH_NAME: feature/new_model_${{ github.run_number }}
        run: |
          gh pr create \
            --base master \
            --head $NEW_BRANCH_NAME \
            --title "Update model.pkl files" \
            --body "Automated update for model.pkl files."
       
      # Step 10: Build Docker Image
      - name: Build Docker Image
        run: docker build -t anmolmishra334/fake_news_detection:${{ github.run_number }} .

      # Step 11: Push Docker Image to DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push anmolmishra334/fake_news_detection:${{ github.run_number }}

      # Step 12: Clear and Prepare Scan Results Folder
      - name: Clear Scan Results Folder
        run: |
          mkdir -p scan_results
          rm -rf scan_results/*
        
      # Step 13: Initialize CodeQL (SonarQube)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      # Step 14: Perform CodeQL Analysis (SonarQube)
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
    
      # Step 15: Pull Trivy Docker Image
      - name: Pull Trivy Docker Image
        run: docker pull aquasec/trivy:latest

      # Step 16: Scan Docker Image for Vulnerabilities
